### ISSUE TITLE
Remote source not available makes local install fails

### ISSUE THREAD

**Issue by ThomasG77** [associatedpress/geomancer#93]
I tried to install a local geomancer server (dev) but I'm unable to browse geographies

The error trace is the following:

```
127.0.0.1 - - [20/May/2015 03:33:15] "GET /geographies HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/thomas/.virtualenvs/geomancer/lib/python2.7/site-packages/raven/middleware.py", line 35, in __call__
    iterable = self.application(environ, start_response)
  File "/home/thomas/.virtualenvs/geomancer/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/thomas/.virtualenvs/geomancer/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thomas/.virtualenvs/geomancer/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thomas/.virtualenvs/geomancer/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thomas/.virtualenvs/geomancer/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thomas/.virtualenvs/geomancer/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thomas/.virtualenvs/geomancer/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thomas/git/geomancer/geomancer/views.py", line 45, in geographies
    geographies, errors = get_geo_types()
  File "/home/thomas/git/geomancer/geomancer/helpers.py", line 52, in get_geo_types
    for col in m.column_info():
  File "/home/thomas/git/geomancer/geomancer/mancers/usa_spending.py", line 85, in column_info
    table = self.fetch_xml(url, params)
  File "/home/thomas/git/geomancer/geomancer/mancers/usa_spending.py", line 99, in fetch_xml
    xml_schema = tree.nsmap[None]
```
In fact, it fails because at `xml_schema = tree.nsmap[None]`, the `tree.nsmap` value is `{}`
This error is due to a "wrong" download. There is a request to an url `http://www.usaspending.gov/faads/faads.php?principal_place_state_code=IL&detail=s`
The answer to this request is `<?xml version='1.0' encoding='UTF-8'?><result numFound='No data found.  The FAADS summary level of detail will be available soon.' />` and so that's why `tree.nsmap` is empty.

Is it possible to make a local fallback (responses to webservice saved) somewhere when the remote data disappears or or is not available

**Comment by cathydeng** [comment]
hey @ThomasG77 - I suspect this is because the USA Spending API is no longer usable, & it is still in the example config file in the available mancers, so it's probably included in your actual config. the example config has been fixed in the code-convening branch, but hasn't been pushed to master yet. all you have to do is delete the one line for USA spending in your config, & it should be working again

**Comment by ThomasG77** [comment]
Hi,

Removing the line was the solution. Thanks for your explanation!
